# Define your protection block below
# Use block type from here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
type = "EMERALD_ORE"

# Another way to refer to the protection stone
# Can be used for /ps give and /ps get
# Must be one word (no spaces)
alias = "64"

# Whether or not to restrict obtaining of the protection stone to only /ps get and /ps give.
# Other ways to obtain this block (ex. mining) will not work as a protection stone.
# Useful to allow the protection block to only be obtained from a shop or command.
# Set to "false" if you want to allow players to obtain a protection stone naturally
restrict_obtaining = true

# Enable or disable the use of this protection stone in specific worlds
# "blacklist" mode prevents this protect block from being used in the worlds in "worlds"
# "whitelist" mode allows this protect block to only be used in the worlds in "worlds"
# Can override with protectionstones.admin permission
world_list_type = "blacklist"
worlds = [
    "exampleworld1",
    "exampleworld2"
]

[region]
    # Protection radius of block
    # Set y_radius to -1 if you want it to protect from sky to bedrock. If this doesn't appear to work set it to 256.
    x_radius = 64
    y_radius = -1
    z_radius = 64

    # How many blocks to offset the default location of /ps home from the protection block
    home_x_offset = 0
    home_y_offset = 1
    home_z_offset = 0

    # Specify the default flags to be set when a new protected region is created.
    flags = [
        "pvp deny",
        "greeting &lEntering &b&l%player%'s &r&lprotected area",
        "farewell &lLeaving &b&l%player%'s &r&lprotected area"
    ]

    # List all the flags that can be set by region owners. Separate them with a comma, no space.
    allowed_flags = [
        "use",
        "pvp",
        "greeting",
        "farewell",
        "mob-spawning",
    ]

    # Default priority type for this block type protection stone
    priority = 0

[block_data]
    # Name given to protection block when obtained with /ps give or /ps get
    # Leave as '' for no name
    display_name = "&a&m<---&r&6 64x64 Protection Stone &r&a&m--->"

    # Lore given to protection block when obtained with /ps give or /ps get
    # Leave as [] for no lore
    lore = [
        "&6(⌐■_■)ノ♪ Nobody's going to touch my stuff!"
    ]

    # Add price when using /ps get
    # Must have compatible economy plugin (requires Vault, ie. Essentials)
    price = 0.0

[behaviour]
    # Hide protection stone right away when placed?
    auto_hide = false

    # Disable returning the block when removed/unclaimed?
    no_drop = false

    # Prevents piston pushing of the block. Recommended to keep as true.
    prevent_piston_push = true

    # Silk Touch: if true, ore-blocks that are also configured by ProtectionStones will disallow Silk Touch drops
    # This was the old behaviour to prevent natural obtaining of the protection stone.
    # Recommended to keep false if "Restrict Obtaining" (the new way) is true
    prevent_silk_touch = false

[player]
    # Whether or not to prevent teleporting into a protected region if the player doesn't own it (except with ender pearl and chorus fruit)
    prevent_teleport_in = false

    # Can't move for x seconds before teleporting with /ps home or /ps tp. Can be disabled with 0.
    # Option to teleport only if player stands still.
    # Can override with permission protectionstones.tp.bypasswait
    no_moving_when_tp_waiting = true
    tp_waiting_seconds = 0

    # Extra permission required to place this specific protection block (you still need protectionstones.create)
    # '' for no extra permission
    permission = ''