#Protection Stones Configuration Page

#Specify the block you want to use to protect regions. Use names from https://goo.gl/EBM8w5
Block: ENDER_STONE

#Specify the default flags to be set when a new protected region is created..
Flags:
  - use deny
  - pvp deny
  - greeting Entering %player%'s protected area
  - farewell Leaving %player%'s protected area

#List all the flags that can be set by region owners. Separate them with a comma, no space.
Allowed Flags: use,pvp,greeting,farewell,mob-spawning

#Protected Region Configuration
Region:
  X Radius: 20
  #Set Y to -1 if you want it to protect from sky to bedrock.
  Y Radius: -1
  Z Radius: 20
  Auto Hide: false
  No Drop: false
  Block Piston: true

#Set priority of all protected regions.
Priority: 0